// Generated by CoffeeScript 1.7.1
var circles, dragend, dragmove, dragstart, edges, force, graph_data, height, node_drag, tick, vis, width;

width = 400;

height = 400;

vis = d3.select('#graph').append('svg');

vis.attr('width', width);

vis.attr('height', height);

graph_data = {};

graph_data['nodes'] = [
  {
    x: 100,
    y: 200
  }, {
    x: 150,
    y: 200
  }, {
    x: 120,
    y: 120
  }
];

graph_data['links'] = [
  {
    source: graph_data['nodes'][0],
    target: graph_data['nodes'][1]
  }, {
    source: graph_data['nodes'][2],
    target: graph_data['nodes'][1]
  }
];

force = d3.layout.force().size([width, height]).nodes(graph_data.nodes).links(graph_data.links).gravity(0.03).distance(100).start();

tick = function() {
  edges.attr('x1', function(d) {
    return d.source.x;
  }).attr('y1', function(d) {
    return d.source.y;
  }).attr('x2', function(d) {
    return d.target.x;
  }).attr('y2', function(d) {
    return d.target.y;
  });
  return circles.attr('cx', function(d) {
    return d.x;
  }).attr('cy', function(d) {
    return d.y;
  });
};

node_drag = d3.behavior.drag().on("dragstart", dragstart).on("drag", dragmove).on("dragend", dragend);

dragstart = function(d, i) {
  return force.stop();
};

dragmove = function(d, i) {
  d.px += d3.event.dx;
  d.py += d3.event.dy;
  d.x += d3.event.dx;
  d.y += d3.event.dy;
  return tick();
};

dragend = function(d, i) {
  tick();
  return force.resume();
};

circles = vis.selectAll("circle").data(graph_data['nodes']).enter().append("circle").attr("class", "node").attr("cx", function(d) {
  return d.x;
}).attr("cy", function(d) {
  return d.y;
}).attr("r", "5").attr("fill", "black").attr("stroke", "#ff0000").call(node_drag);

edges = vis.selectAll("line").data(graph_data['links']).enter().append("line").attr("x1", function(d) {
  return d.source.x;
}).attr("y1", function(d) {
  return d.source.y;
}).attr("x2", function(d) {
  return d.target.x;
}).attr("y2", function(d) {
  return d.target.y;
}).style("stroke", "rgb(6,120,155)");

force.on("tick", tick);

//# sourceMappingURL=main.map
